version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      all-packages:
        patterns: ['*']
      security-packages:
        applies-to: security-updates
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      all-actions:
        patterns: ['*']
      security-actions:
        applies-to: security-updates
        patterns: ['*']
